version: "3.8"

services:
    php:
        container_name: ok_php
        build:  docker/php-fpm/
        volumes:
            - ./server:/var/www/server
        depends_on:
            -  postgres
        env_file:
            - .env

    postgres:  
        container_name: ok_postgres
        build: docker/postgres/
        volumes:
            - database:/var/lib/postgresql/data
            - ./docker/postgres/dumps/:/tmp/  
        ports:  
            - 54321:5432
        environment:
            - LC_ALL=C.UTF-8
            - POSTGRES_DB=docker 
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=docker

    nginx:    
        container_name: ok_nginx     
        build:  docker/nginx/
        volumes:
            - ./server:/var/www/server
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/sites/:/etc/nginx/sites-available
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d
            - ./docker/certbot/www:/var/www/certbot/:ro
            - ./docker/certbot/conf/:/etc/nginx/ssl/:ro
        depends_on:
            - php
        ports:  
            - "80:80"
            - "81:81"

    certbot:
        image: certbot/certbot
        volumes:
        - ./docker/certbot/www/:/var/www/certbot/:rw
        - ./docker/certbot/conf/:/etc/letsencrypt/:rw
            
volumes:
    database:
        driver: local